spring.application.name=usp3

spring.datasource.url=jdbc:postgresql://localhost:5432/usp3
spring.datasource.username=postgres
spring.datasource.password=goal2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.tool.hbm2ddl=TRACE
logging.level.org.hibernate.tool.hbm2ddl=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
